title: Hackkery's Blog
description: "Hackkery's Super Secret Security Blog"
author:
  name: "Hackkery"
  email: "hackkery@protonmail.com"
  url: "https://hackkery.com/blog"

baseurl: /

source: .
destination: ./_site
permalink: /:title
paginate: 5
paginate_path: /page/:num/

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

future: true
plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap

# Custom variables
owner : "Hackkery"
year : "2020"
